### ISSUE TITLE
平台多久上线啊？

### ISSUE THREAD

**Issue by zguiyang** [ao-space/platform-base#1]
迫不及待的体验一下了

**Comment by yuandaqing2009** [comment]
@zguiyang 基础平台已经是开源的，可以按照readme里的操作流程进行安装部署

**Comment by aospace-admin** [comment]
@zguiyang 傲空间平台基础功能已开源，可根据readme里的操作步骤进行安装，使用需配合设备交付件一起部署，设备交付件项目正在进行中，上线后将第一时间通知您~
