### ISSUE TITLE
文档注释的参数与方法不一致

### ISSUE THREAD

**Issue by NicoAsuka** [ao-space/platform-base#11]
- [x] I have searched the [issues](https://github.com/ao-space/platform-base/issues) of this repository and believe that this is not a duplicate.

代码内的文档注释的参数与方法参数不一致，出现错误的类的路径是                                                                                         

eulixplatform-registry/src/main/java/xyz/eulix/platform/services/network/rest/NetworkResource.java

![image](https://github.com/ao-space/platform-base/assets/109805982/239c1c99-e61a-4d64-860e-1733d29d6871)

**Comment by gatsby068** [comment]
问题已解决，关闭issue
