### ISSUE TITLE
中文文档的图片路径错误

### ISSUE THREAD

**Issue by NicoAsuka** [ao-space/platform-base#9]
- [x] I have searched the [issues](https://github.com/ao-space/platform-base/issues) of this repository and believe that this is not a duplicate.

浏览仓库过程中我发现项目的中文文档的图片好像挂了，应该是图片路径写错了，zh写成zn了
![image](https://github.com/ao-space/platform-base/assets/109805982/3b6d2020-d76b-4d41-b5f6-4cb228fdfe9e)
![image](https://github.com/ao-space/platform-base/assets/109805982/5e8636c3-8c39-4c51-8936-71072c64a516)
修改后：
![image](https://github.com/ao-space/platform-base/assets/109805982/36ebabb3-6136-488d-9037-1fdddbf864fc)

**Comment by jimmieme** [comment]
@NicoAsuka 感谢提醒，已提交 PR #10 处理。
